parameters:
    # Adds a fallback APP_ENCRYPTION_KEY if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(APP_ENCRYPTION_KEY): ''

services:
    MediaMonks\Doctrine\Transformable\Transformer\PhpHashTransformer:
        arguments:
            - binary: false

    MediaMonks\Doctrine\Transformable\Transformer\DefuseCryptoEncryptKeyTransformer:
        lazy: true
        arguments: ['%env(APP_ENCRYPTION_KEY)%', { binary: false }]

    MediaMonks\Doctrine\Transformable\Transformer\TransformerPool:
        public: true
        calls:
            - [set, ['hash', '@MediaMonks\Doctrine\Transformable\Transformer\PhpHashTransformer']]
            - [set, ['encrypt', '@MediaMonks\Doctrine\Transformable\Transformer\DefuseCryptoEncryptKeyTransformer']]

    MediaMonks\Doctrine\Transformable\TransformableSubscriber:
        arguments:
            - '@MediaMonks\Doctrine\Transformable\Transformer\TransformerPool'
        tags:
         - { name: doctrine.event_subscriber, priority: 100}
