admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /%admin_path%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /%admin_path%

admin_login:
    path: /%admin_path%/login
    controller: App\Controller\Admin\SecurityController::loginAction

admin_logout:
    path: /%admin_path%/logout
    controller: App\Controller\Admin\SecurityController::logoutAction
